zookeeper:
  image: mesoscloud/zookeeper:3.4.6-centos-7
  ports:
    - "2181:2181"
    - "2888:2888"
    - "3888:3888"
  environment:
    SERVERS: 'server.1=127.0.0.1'
    MYID: '1'

mesosmaster:
  image: mesosphere/mesos-master:1.0.0
  net: host
  volumes:
    - /var/log/mesos/master
  environment:
    MESOS_ZK: 'zk://localhost:2181/mesos'
    MESOS_QUORUM: '1'
    MESOS_CLUSTER: 'local'
    MESOS_HOSTNAME: 'localhost'
    MESOS_LOG_DIR: '/var/log/mesos/master'

mesosslave:
  image: mesosphere/mesos-slave:1.0.0
  net: host
  privileged: true
  volumes:
    - /var/log/mesos/slave
    - /sys:/sys
# /cgroup is needed on some older Linux versions
#    - /cgroup:/cgroup
# /usr/bin/docker is needed if you're running an older docker version
#    - /usr/local/bin/docker:/usr/bin/docker:r
    - /var/run/docker.sock:/var/run/docker.sock:rw
  environment:
    MESOS_MASTER: 'zk://localhost:2181/mesos'
    MESOS_PORT: '5051'
    MESOS_LOG_DIR: '/var/log/mesos/slave'
    MESOS_CONTAINERIZERS: 'docker,mesos'
    MESOS_EXECUTOR_REGISTRATION_TIMEOUT: '5mins'
    MESOS_EXECUTOR_SHUTDOWN_GRACE_PERIOD: '90secs'
    MESOS_DOCKER_STOP_TIMEOUT: '60secs'
    MESOS_WORK_DIR: '/tmp'
# If your workstation doesn't have a resolvable hostname/FQDN then $MESOS_HOSTNAME needs to be set to its IP-address
#    MESOS_HOSTNAME: 10.87.1.123

marathon:
  image: mesosphere/marathon:v1.3.3
  net: host
  environment:
    MARATHON_ZK: 'zk://localhost:2181/marathon'
    MARATHON_MASTER: 'zk://localhost:2181/mesos'
    MARATHON_EVENT_SUBSCRIBER: 'http_callback'
    MARATHON_TASK_LAUNCH_TIMEOUT: '300000'

marathonsubmit:
  build: marathon-submit
  net: host
  environment:
    MARATHON_URL: http://localhost:8080
  volumes:
    - './marathon-submit:/submit'
# Enables using local development repo of lighter
#    - '../lighter:/lighter'

chronos:
  image: mesosphere/chronos:chronos-2.5.0-0.1.20160223054243.ubuntu1404-mesos-0.27.1-2.0.226.ubuntu1404
  command: '/usr/bin/chronos run_jar --http_port 4400 --zk_hosts localhost:2181 --master zk://localhost:2181/mesos'
  net: host

chronossubmit:
  build: chronos-submit
  net: host
  environment:
    CHRONOS_URL: 'http://localhost:4400'

gateway:
  image: meltwater/proxymatic:latest
#  build: ../proxymatic
  net: host
  environment:
    MARATHON_URL: 'http://localhost:8080'
    EXPOSE_HOST: 'true'
    VHOST_DOMAIN: 'localdomain'
    VERBOSE: 'true'

secretary:
  image: meltwater/secretary:latest
  net: host
  volumes:
    - './marathon-submit/site/keys:/keys'
